const placeholderAvatar =
  "https://cdn-icons-png.flaticon.com/512/3135/3135715.png";

export const data = [
  {
    id: 4,
    name: "Gilbert Friesen",
    company: "Hartmann Inc",
    email: "yfriesen@example.com",
    phone: "231-876-9931",
    value: "$5,000",
    tags: [],
    assigned: placeholderAvatar,
    status: "New",
    source: "Facebook",
    lastContact: "13 hr",
    createdAt: "2025-08-01",
  },
  {
    id: 24,
    name: "Javon Schaden",
    company: "Nienow, Green and Marvin",
    email: "pstark@example.org",
    phone: "843.986.5138",
    value: "$8,000",
    tags: [],
    assigned: placeholderAvatar,
    status: "Qualified",
    source: "Facebook",
    lastContact: "13 hr",
    createdAt: "2025-08-01",
  },
  {
    id: 40,
    name: "Jovanny Goyette",
    company: "Bode PLC",
    email: "botsford.enrico@example.net",
    phone: "+1.225.608.1567",
    value: "$12,000",
    tags: ["follow up", "tomorrow"],
    assigned: placeholderAvatar,
    status: "Qualified",
    source: "Facebook",
    lastContact: "13 hr",
    createdAt: "2025-08-01",
  },
  {
    id: 52,
    name: "Amelia Rodriguez",
    company: "Tech Solutions Ltd",
    email: "amelia.rod@example.com",
    phone: "555-123-4567",
    value: "$15,000",
    tags: ["urgent", "proposal"],
    assigned: placeholderAvatar,
    status: "Contacted",
    source: "LinkedIn",
    lastContact: "2 hr",
    createdAt: "2025-08-02",
  },
  {
    id: 67,
    name: "Marcus Johnson",
    company: "Global Enterprises",
    email: "marcus.j@globalent.com",
    phone: "555-987-6543",
    value: "$25,000",
    tags: ["high value"],
    assigned: placeholderAvatar,
    status: "Qualified",
    source: "Referral",
    lastContact: "1 day",
    createdAt: "2025-07-28",
  },
  {
    id: 81,
    name: "Sophia Chen",
    company: "Innovate Co",
    email: "sophia.chen@innovate.co",
    phone: "555-456-7890",
    value: "$7,500",
    tags: ["demo scheduled"],
    assigned: placeholderAvatar,
    status: "New",
    source: "Website",
    lastContact: "30 min",
    createdAt: "2025-08-03",
  },
  {
    id: 93,
    name: "David Wilson",
    company: "Prime Industries",
    email: "dwilson@primeind.com",
    phone: "555-321-0987",
    value: "$30,000",
    tags: ["contract ready"],
    assigned: placeholderAvatar,
    status: "Qualified",
    source: "Email Campaign",
    lastContact: "5 hr",
    createdAt: "2025-07-30",
  },
  {
    id: 105,
    name: "Emma Thompson",
    company: "Creative Solutions",
    email: "emma.t@creativesol.com",
    phone: "555-654-3210",
    value: "$4,200",
    tags: [],
    assigned: placeholderAvatar,
    status: "Contacted",
    source: "Google Ads",
    lastContact: "1 day",
    createdAt: "2025-08-01",
  },
  {
    id: 118,
    name: "Robert Garcia",
    company: "Future Tech",
    email: "robert.g@futuretech.io",
    phone: "555-789-0123",
    value: "$18,000",
    tags: ["follow up", "next week"],
    assigned: placeholderAvatar,
    status: "Qualified",
    source: "Trade Show",
    lastContact: "3 hr",
    createdAt: "2025-08-02",
  },
  {
    id: 132,
    name: "Olivia Parker",
    company: "Digital Dynamics",
    email: "olivia.p@digitaldyn.com",
    phone: "555-234-5678",
    value: "$9,800",
    tags: ["interested"],
    assigned: placeholderAvatar,
    status: "New",
    source: "Instagram",
    lastContact: "6 hr",
    createdAt: "2025-08-03",
  },
  {
    id: 145,
    name: "Michael Brown",
    company: "Enterprise Solutions",
    email: "michael.b@entsol.com",
    phone: "555-876-5432",
    value: "$22,500",
    tags: ["proposal sent"],
    assigned: placeholderAvatar,
    status: "Contacted",
    source: "Referral",
    lastContact: "2 days",
    createdAt: "2025-07-29",
  },
  {
    id: 158,
    name: "Isabella Martinez",
    company: "Smart Systems",
    email: "isabella.m@smartsys.com",
    phone: "555-345-6789",
    value: "$6,300",
    tags: [],
    assigned: placeholderAvatar,
    status: "New",
    source: "Website",
    lastContact: "45 min",
    createdAt: "2025-08-03",
  },
  {
    id: 171,
    name: "William Davis",
    company: "Tech Innovations",
    email: "william.d@techinnov.com",
    phone: "555-567-8901",
    value: "$35,000",
    tags: ["high priority", "decision maker"],
    assigned: placeholderAvatar,
    status: "Qualified",
    source: "LinkedIn",
    lastContact: "1 hr",
    createdAt: "2025-08-03",
  },
];
