// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zoninfaxfxtxcannieeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvbmluZmF4Znh0eGNhbm5pZWVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTA4NTksImV4cCI6MjA2NDUyNjg1OX0.NHkzxX0-O0WI_xxEHbdaPsbQKZPPaVISzs4-p9SPjl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);